"""Initial migration

Revision ID: c9799acf8e82
Revises: 
Create Date: 2025-11-25 20:08:14.500820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9799acf8e82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('source_game_1', sa.Integer(), nullable=True),
    sa.Column('source_game_2', sa.Integer(), nullable=True),
    sa.Column('team_1_id', sa.Integer(), nullable=True),
    sa.Column('team_2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('game_time', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('user_picks',
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('predicted_winner_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pick_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=True),
    sa.Column('hash_algo', sa.String(length=10), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_picks')
    op.drop_table('teams')
    op.drop_table('games')
    # ### end Alembic commands ###
